spring:
  datasource:
    username: botuser
    password: ${DB_PASSWORD}
  application:
    name: gitsync
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

github:
  oauth:
    client-id: ${GITHUB_CLIENT_ID}
    client-secret: ${GITHUB_CLIENT_SECRET}
    callback-route: /api/oauth/github/callback
  api:
    base-url: https://api.github.com
    base-public-url: https://github.com

encryption:
  secret:
    key: ${GITSYNC_ENCRYPTION_KEY}